name: Build and Export Artifacts

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk
      
    - name: Create Android Release
      id: create_release_android
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
        tag_name: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        body: Release ${{ github.run_number }}
        draft: false
        prerelease: false
        
  build-ios:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build IPA
      run: flutter build ios --release --no-codesign
      
    - name: Create iOS Release
      id: create_release_ios
      uses: softprops/action-gh-release@v1
      with:
        files: build/ios/archive/Runner.ipa
        tag_name: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        body: Release ${{ github.run_number }}
        draft: false
        prerelease: false
